/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author natas
 */
public class DetallesProducto extends javax.swing.JFrame {
    
    private String producto;
    
    /**
     * Creates new form DetallesProducto
     */
    public DetallesProducto(String producto) {
        this.producto = producto;
        initComponents();
        
        txtNombreProducto.setText(producto);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupTamaño = new javax.swing.ButtonGroup();
        btnGrupSabores = new javax.swing.ButtonGroup();
        panFondoRosa = new javax.swing.JPanel();
        panFondoBlanco = new javax.swing.JPanel();
        panLogo = new javax.swing.JPanel();
        txtProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JLabel();
        panSeparador1 = new javax.swing.JPanel();
        txtNombreProducto1 = new javax.swing.JLabel();
        radTamChico = new javax.swing.JRadioButton();
        radTamMediano = new javax.swing.JRadioButton();
        radTamGrande = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        panSeparador2 = new javax.swing.JPanel();
        txtNombreProducto2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        panSeparador16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondoRosa.setBackground(new java.awt.Color(233, 215, 248));

        panFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panLogoLayout = new javax.swing.GroupLayout(panLogo);
        panLogo.setLayout(panLogoLayout);
        panLogoLayout.setHorizontalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panLogoLayout.setVerticalGroup(
            panLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        txtProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtProducto.setText("Producto:");

        txtNombreProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto.setText("Nombre del producto");

        javax.swing.GroupLayout panSeparador1Layout = new javax.swing.GroupLayout(panSeparador1);
        panSeparador1.setLayout(panSeparador1Layout);
        panSeparador1Layout.setHorizontalGroup(
            panSeparador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSeparador1Layout.setVerticalGroup(
            panSeparador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtNombreProducto1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto1.setText("Tamaño");

        radTamChico.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupTamaño.add(radTamChico);
        radTamChico.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        radTamChico.setText("Chico ");

        radTamMediano.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupTamaño.add(radTamMediano);
        radTamMediano.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        radTamMediano.setText("Mediano");

        radTamGrande.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupTamaño.add(radTamGrande);
        radTamGrande.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        radTamGrande.setText("Grande");

        btnCancelar.setBackground(new java.awt.Color(226, 183, 252));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSeparador2Layout = new javax.swing.GroupLayout(panSeparador2);
        panSeparador2.setLayout(panSeparador2Layout);
        panSeparador2Layout.setHorizontalGroup(
            panSeparador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSeparador2Layout.setVerticalGroup(
            panSeparador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtNombreProducto2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto2.setText("Sabores");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupSabores.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton4.setText("Chico ");

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupSabores.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton5.setText("Chico ");

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupSabores.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton6.setText("Chico ");

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupSabores.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton7.setText("Chico ");

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupSabores.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton8.setText("Chico ");

        javax.swing.GroupLayout panSeparador16Layout = new javax.swing.GroupLayout(panSeparador16);
        panSeparador16.setLayout(panSeparador16Layout);
        panSeparador16Layout.setHorizontalGroup(
            panSeparador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSeparador16Layout.setVerticalGroup(
            panSeparador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panFondoBlancoLayout = new javax.swing.GroupLayout(panFondoBlanco);
        panFondoBlanco.setLayout(panFondoBlancoLayout);
        panFondoBlancoLayout.setHorizontalGroup(
            panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(txtNombreProducto1))
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radTamMediano)
                                    .addComponent(radTamChico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radTamGrande, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(txtNombreProducto2))
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioButton8))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panSeparador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addComponent(panLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                        .addComponent(txtNombreProducto)
                                        .addGap(0, 17, Short.MAX_VALUE))
                                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                        .addComponent(txtProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancelar)
                                        .addGap(8, 8, 8))))
                            .addComponent(panSeparador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panSeparador16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panFondoBlancoLayout.setVerticalGroup(
            panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProducto)
                            .addComponent(btnCancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProducto))
                    .addComponent(panLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radTamChico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radTamMediano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radTamGrande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panSeparador16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panFondoRosaLayout = new javax.swing.GroupLayout(panFondoRosa);
        panFondoRosa.setLayout(panFondoRosaLayout);
        panFondoRosaLayout.setHorizontalGroup(
            panFondoRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoRosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panFondoRosaLayout.setVerticalGroup(
            panFondoRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoRosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondoRosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondoRosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        JMenuPrincipal jmp = new JMenuPrincipal();
        jmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrupSabores;
    private javax.swing.ButtonGroup btnGrupTamaño;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JPanel panFondoBlanco;
    private javax.swing.JPanel panFondoRosa;
    private javax.swing.JPanel panLogo;
    private javax.swing.JPanel panSeparador1;
    private javax.swing.JPanel panSeparador10;
    private javax.swing.JPanel panSeparador11;
    private javax.swing.JPanel panSeparador12;
    private javax.swing.JPanel panSeparador15;
    private javax.swing.JPanel panSeparador16;
    private javax.swing.JPanel panSeparador2;
    private javax.swing.JPanel panSeparador3;
    private javax.swing.JPanel panSeparador4;
    private javax.swing.JPanel panSeparador5;
    private javax.swing.JPanel panSeparador6;
    private javax.swing.JPanel panSeparador7;
    private javax.swing.JPanel panSeparador8;
    private javax.swing.JPanel panSeparador9;
    private javax.swing.JRadioButton radTamChico;
    private javax.swing.JRadioButton radTamGrande;
    private javax.swing.JRadioButton radTamMediano;
    private javax.swing.JLabel txtNombreProducto;
    private javax.swing.JLabel txtNombreProducto1;
    private javax.swing.JLabel txtNombreProducto2;
    private javax.swing.JLabel txtProducto;
    // End of variables declaration//GEN-END:variables
}
