/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.mycompany.heladeriaconsultar.CasoConsultar;
import com.mycompany.iheladeriaconsultar.ICasoConsultar;
import dto.ProductoDTO;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class FormProductos extends javax.swing.JFrame {
    private List<ProductoDTO> productosDTO;
    private ICasoConsultar casoConsultar;
    List<ProductoDTO> productoDTOs;
    /**
     * Creates new form FormProductos
     */
    public FormProductos() {
        casoConsultar=new CasoConsultar();
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        productoDTOs = casoConsultar.consultarTodosProductos();
        JFrame menu=this;
        
        for (int i = 0; i < productoDTOs.size(); i++) {
            JButton boton = new JButton(productoDTOs.get(i).getNombre());
            boton.setPreferredSize(new Dimension(295, 200));
            boton.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    FormEditarProducto editarProducto=new FormEditarProducto(boton.getText());
                    menu.dispose();

                }
            });
            panel.add(boton);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        regresarButton = new javax.swing.JButton();
        anadirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new java.awt.GridLayout(0, 2));
        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 610, 430));

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 130, 50));

        anadirButton.setText("Añadir");
        anadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(anadirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        // TODO add your handling code here:
        JMenuPrincipal menuPrincipal=new JMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void anadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirButtonActionPerformed
        // TODO add your handling code here:
        FormAgregarNombre agregarNombre=new FormAgregarNombre();
        agregarNombre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_anadirButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
}
