package presentacion;

import dto.DetalleProductoDTO;
import dto.ProductoDTO;
import dto.TamanoDTO;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author natas
 */
public class ProductoAdquirido extends javax.swing.JFrame {

    private ProductoDTO productoDTO;
    private List<DetalleProductoDTO> listaDetallesProductos;
    private DetalleProductoDTO detalleProductoDTO;
    private String tamano;
    private Float precio;
    private String sabor;
    JMenuPrincipal menu;

    /**
     * Creates new form DetallesProducto
     */
    public ProductoAdquirido(ProductoDTO productoDTO, List<DetalleProductoDTO> listaDetallesProductos) {
        this.menu = menu;
        this.listaDetallesProductos = listaDetallesProductos;
        this.productoDTO = productoDTO;
        this.detalleProductoDTO = new DetalleProductoDTO();

        initComponents();

        ActionListener listenerTam = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                // Desseleccionar los demás checkboxes cuando uno es seleccionado
                if (e.getSource() instanceof JCheckBox) {
                    JCheckBox selectedCheckBox = (JCheckBox) e.getSource();
                    if (selectedCheckBox.isSelected()) {
                        tamano = selectedCheckBox.getName();
                        precio = Float.parseFloat(obtenerPrecio(selectedCheckBox.getText()));
                        for (Component component : panelTamano.getComponents()) {
                            if (component instanceof JCheckBox && component != selectedCheckBox) {
                                ((JCheckBox) component).setSelected(false);
                            }
                        }
                    }
                }
            }
        };

        List<TamanoDTO> tamanos = productoDTO.getTamano();
        for (TamanoDTO t : tamanos) {
            JCheckBox checkbox = new JCheckBox(t.getNombreTamano() + " $" + t.getPrecioBase());
            checkbox.setName(t.getNombreTamano());
            checkbox.setPreferredSize(new Dimension(340, 50));
            checkbox.addActionListener(listenerTam);
            panelTamano.add(checkbox);
        }
        ActionListener listenerSab = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (e.getSource() instanceof JCheckBox) {
                    JCheckBox selectedCheckBox = (JCheckBox) e.getSource();
                    if (selectedCheckBox.isSelected()) {
                        sabor = selectedCheckBox.getText();
                        for (Component component : panelSabor.getComponents()) {
                            if (component instanceof JCheckBox && component != selectedCheckBox) {
                                ((JCheckBox) component).setSelected(false);
                            }
                        }
                    }
                }
            }
        };
        List<String> sabores = productoDTO.getSabores();
        for (String s : sabores) {
            JCheckBox checkbox = new JCheckBox(s);
            checkbox.setPreferredSize(new Dimension(340, 50));
            checkbox.addActionListener(listenerSab);
            panelSabor.add(checkbox);
        }

        this.setLocationRelativeTo(null);
        txtNombreProducto.setText(productoDTO.getNombre());
        this.setVisible(true);

    }

    public String obtenerPrecio(String texto) {
        int indiceSignoDolar = texto.indexOf("$");
        if (indiceSignoDolar != -1 && indiceSignoDolar < texto.length() - 1) {
            String textoDespuesDelSignoDolar = texto.substring(indiceSignoDolar + 1);
            textoDespuesDelSignoDolar = textoDespuesDelSignoDolar.trim();
            return textoDespuesDelSignoDolar;
        } else {
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupTamaño = new javax.swing.ButtonGroup();
        btnGrupSabores = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panFondoRosa = new javax.swing.JPanel();
        panFondoBlanco = new javax.swing.JPanel();
        txtProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JLabel();
        panSeparador1 = new javax.swing.JPanel();
        txtNombreProducto1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        panSeparador2 = new javax.swing.JPanel();
        txtNombreProducto2 = new javax.swing.JLabel();
        panSeparador16 = new javax.swing.JPanel();
        txtNombreProducto3 = new javax.swing.JLabel();
        radTamToping = new javax.swing.JRadioButton();
        panSeparador17 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JLabel();
        txfCantidad = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelTamano = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelSabor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondoRosa.setBackground(new java.awt.Color(233, 215, 248));

        panFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        txtProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtProducto.setText("Producto:");

        txtNombreProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto.setText("Nombre del producto");

        javax.swing.GroupLayout panSeparador1Layout = new javax.swing.GroupLayout(panSeparador1);
        panSeparador1.setLayout(panSeparador1Layout);
        panSeparador1Layout.setHorizontalGroup(
            panSeparador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        panSeparador1Layout.setVerticalGroup(
            panSeparador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtNombreProducto1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto1.setText("Tamaño");

        btnCancelar.setBackground(new java.awt.Color(226, 183, 252));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSeparador2Layout = new javax.swing.GroupLayout(panSeparador2);
        panSeparador2.setLayout(panSeparador2Layout);
        panSeparador2Layout.setHorizontalGroup(
            panSeparador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSeparador2Layout.setVerticalGroup(
            panSeparador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtNombreProducto2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto2.setText("Sabores");

        javax.swing.GroupLayout panSeparador16Layout = new javax.swing.GroupLayout(panSeparador16);
        panSeparador16.setLayout(panSeparador16Layout);
        panSeparador16Layout.setHorizontalGroup(
            panSeparador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSeparador16Layout.setVerticalGroup(
            panSeparador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtNombreProducto3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtNombreProducto3.setText("Topings");

        radTamToping.setBackground(new java.awt.Color(255, 255, 255));
        radTamToping.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        radTamToping.setText("Si");
        radTamToping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTamTopingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSeparador17Layout = new javax.swing.GroupLayout(panSeparador17);
        panSeparador17.setLayout(panSeparador17Layout);
        panSeparador17Layout.setHorizontalGroup(
            panSeparador17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panSeparador17Layout.setVerticalGroup(
            panSeparador17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        txtCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtCantidad.setText("Cantidad");

        txfCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCantidadActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(226, 183, 252));
        btnAceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        panelTamano.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(panelTamano);

        panelSabor.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane3.setViewportView(panelSabor);

        javax.swing.GroupLayout panFondoBlancoLayout = new javax.swing.GroupLayout(panFondoBlanco);
        panFondoBlanco.setLayout(panFondoBlancoLayout);
        panFondoBlancoLayout.setHorizontalGroup(
            panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panSeparador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panSeparador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(txtNombreProducto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreProducto)
                                    .addComponent(txtProducto)))
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(txtNombreProducto2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(txtNombreProducto3))
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad))
                                .addGap(18, 18, 18)
                                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radTamToping))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panSeparador17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panSeparador16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panFondoBlancoLayout.setVerticalGroup(
            panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(panSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(panSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(txtNombreProducto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoBlancoLayout.createSequentialGroup()
                                .addComponent(txtProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreProducto)
                                .addGap(44, 44, 44)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtNombreProducto2)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(panSeparador16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(panSeparador17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFondoBlancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProducto3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radTamToping)
                        .addGap(27, 27, 27)
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfCantidad)
                            .addComponent(txtCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panFondoRosaLayout = new javax.swing.GroupLayout(panFondoRosa);
        panFondoRosa.setLayout(panFondoRosaLayout);
        panFondoRosaLayout.setHorizontalGroup(
            panFondoRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoRosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panFondoRosaLayout.setVerticalGroup(
            panFondoRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoRosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondoRosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondoRosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //JOptionPane.showMessageDialog(rootPane, "Se agrego el producto correctamente");
        // Se agrego de mientras 33 de flotante
        Integer cantidad = Integer.parseInt(txfCantidad.getText());
        DetalleProductoDTO detalleProducto = new DetalleProductoDTO(productoDTO.getNombre(), sabor, tamano, precio, cantidad, radTamToping.isSelected(), 33.0f);

        listaDetallesProductos.add(detalleProducto);
        JMenuPrincipal menu = new JMenuPrincipal();
        menu.actualizarTable(listaDetallesProductos);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void radTamTopingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTamTopingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radTamTopingActionPerformed

    private void txfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCantidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrupSabores;
    private javax.swing.ButtonGroup btnGrupTamaño;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panFondoBlanco;
    private javax.swing.JPanel panFondoRosa;
    private javax.swing.JPanel panSeparador1;
    private javax.swing.JPanel panSeparador16;
    private javax.swing.JPanel panSeparador17;
    private javax.swing.JPanel panSeparador2;
    private javax.swing.JPanel panelSabor;
    private javax.swing.JPanel panelTamano;
    private javax.swing.JRadioButton radTamToping;
    private javax.swing.JTextField txfCantidad;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtNombreProducto;
    private javax.swing.JLabel txtNombreProducto1;
    private javax.swing.JLabel txtNombreProducto2;
    private javax.swing.JLabel txtNombreProducto3;
    private javax.swing.JLabel txtProducto;
    // End of variables declaration//GEN-END:variables
}
